---
- hosts: localhost
  tasks:
    - name: Set proxy
      command: export http_proxy=http://one.verizon.com:80;export https_proxy=http://one.verizon.com:80

    - name: Download JDK
      get_url:
         url: http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/jdk-8u162-linux-x64.tar.gz
         headers: "Cookie: oraclelicense=accept-securebackup-cookie"
         dest: /tmp

    - name: Extract JDK
      command: tar xzf /tmp/jdk-8u162-linux-x64.tar.gz -C /opt

    - name: Set JAVA_HOME
      command: export JAVA_HOME=/opt/jdk1.8.0_162

    - name: Download tomcat
      get_url:
         url: http://www.trieuvan.com/apache/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz
         dest: /tmp

    - name: Extract Tomcat
      command: tar xzf /tmp/apache-tomcat-8.5.29.tar.gz -C /opt

    - name: set CATALINA_HOME
      command: export CATALINA_HOME:/opt/apache-tomcat-8.5.29

    - name: Set path
      command: export PATH=$PATH:$JAVA_HOME:$CATALINA_HOME

    - name: Start tomcat
      command: /opt/apache-tomcat-8.5.29/bin/startup.sh

    - name: Download application
      command: echo 'Hello'

